kind: Service
apiVersion: v1
metadata:
  name: mysql-group-replication-master
  labels:
    run: master
spec:
  selector:
    run: master
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  - name: mysql-replication
    protocol: TCP
    port: 3406
    targetPort: 3406