kind: Service
apiVersion: v1
metadata:
  name: mysql-group-replication-scalable-master
  labels:
    run: scalable-master
spec:
  selector:
    run: scalable-master
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  - name: mysql-replication
    protocol: TCP
    port: 33061
    targetPort: 33061