apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-group-replication-master
  labels:
    run: master
spec:
  replicas: 1
  selector:
    run: master
  template:
    metadata:
      labels:
        run: master
    spec:
      containers:
        - name: master
          image: mysql-group-replication-master:1.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "test"
            - name: MYSQL_REPLICATION_USERNAME
              value: 'demo'
            - name: MYSQL_REPLICATION_PASSWORD
              value: 'demo'
            - name: GROUP_UUID
              value: '291C7A80-2768-42DE-9CBD-2407A9A56D32'